language: java
jdk: openjdk8
sudo: false

# We enable a virtual display to prevent ImageJ from running in headless mode
dist: xenial
services:
  - xvfb

cache:
  directories:
    - $HOME/.m2/

stages:
  - compile
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: compile
    - script: mvn compile
    - stage: test
    - script: mvn test
    - stage: deploy
    - script: ./deploy.sh