language: java
jdk: openjdk8
sudo: false

# We enable a virtual display to prevent ImageJ from running in headless mode
dist: xenial
services:
  - xvfb

cache:
  directories:
    - $HOME/.m2/

script: mvn clean verify

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master